apiVersion: v1
kind: Service
metadata:
  labels:
   operator: proactive-node-scaling-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: proactive-node-scaling-operator-certs
  name: controller-manager-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    operator: proactive-node-scaling-operator
